config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :estampas do
  	collection do
  		get 'search'
  	end
  	  resources :reviews, except: [:show, :index]
	end

  root 'estampas#index'

end

app/models/estampa.rb
class Estampa < ActiveRecord::Base
searchkick
belongs_to :user
has_many :reviews
	
	has_attached_file :image, styles: { medium: "400x600#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :estampa
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :estampas 
  has_many :reviews, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estampas_controller.rb
class EstampasController < ApplicationController
  before_action :set_estampa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @estampas = Estampa.search(params[:search])
    else
      @estampas = Estampa.all
  end
  end
      
  def index
    @estampas = Estampa.all
  end

  def show
    @reviews = Review.where(estampa_id: @estampa.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @estampa = current_user.estampas.build
  end

  def edit
  end

  def create
    @estampa = current_user.estampas.build(estampa_params)

    respond_to do |format|
      if @estampa.save
        format.html { redirect_to @estampa, notice: 'estampa was successfully created.' }
        format.json { render :show, status: :created, location: @estampa }
      else
        format.html { render :new }
        format.json { render json: @estampa.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @estampa.update(estampa_params)
        format.html { redirect_to @estampa, notice: 'estampa was successfully updated.' }
        format.json { render :show, status: :ok, location: @estampa }
      else
        format.html { render :edit }
        format.json { render json: @estampa.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @estampa.destroy
    respond_to do |format|
      format.html { redirect_to estampas_url, notice: 'estampa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_estampa
      @estampa = Estampa.find(params[:id])
    end

    def estampa_params
      params.require(:estampa).permit(:title, :description, :criador, :rating, :image)
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_estampa
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.estampa_id = @estampa.id

    if @review.save
      redirect_to @estampa
    else
      render 'new'
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_estampa
      @estampa = Estampa.find(params[:estampa_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estampas_helper.rb
module EstampasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/estampas/_form.html.erb
<%= form_for @estampa, html: { multipart: true } do |f| %>
  <% if @estampa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estampa.errors.count, "error") %> prohibited this estampa from being saved:</h2>

      <ul>
      <% @estampa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :criador %><br>
    <%= f.text_field :criador %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estampas/edit.html.erb
<h1>Editing Estampa</h1>

<%= render 'form' %>

<%= link_to 'Show', @estampa %> |
<%= link_to 'Back', estampas_path %>

app/views/estampas/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>As estampas mais iradas aqui!</h1>
    <p>Avalie suas estampas, leia as avaliações e participe das discuções. </p>
    <p><%= link_to "Cadastre-se para avaliar o review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @estampas.each do |estampa| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag estampa.image.url(:medium), class: 'image'), estampa %>
      </div>
    </div>
  <% end %>
</div>

app/views/estampas/new.html.erb
<h1>New Estampa</h1>

<%= render 'form' %>

<%= link_to 'Back', estampas_path %>

app/views/estampas/search.html.erb
<div class="row">
  <% @estampas.each do |estampa| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag estampa.image.url(:medium), class: 'image'), estampa %>
      </div>
    </div>
  <% end %>
</div>

app/views/estampas/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @estampa.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @estampa.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @estampa.description %></td>
              </tr>
              <tr>
                <td><strong>Criador:</strong></td>
                <td><%= @estampa.criador %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @estampa.rating %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_estampa_review_path(@estampa) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @estampa.title %></h1>
        <p><%= @estampa.description %></p>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_estampa_review_path(@estampa), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_estampa_path(@estampa) %> |
<%= link_to 'Back', estampas_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Estampas", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New estampa", new_estampa_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_estampas_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VandalReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">	
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@estampa, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', "#" %> |
<%= link_to 'Back', "#" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', estampa_path(@estampa) %>